import 'package:flutter/material.dart';

import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:provider/provider.dart';

class dummyDataProvider with ChangeNotifier {
  List<String> get state {
    return [..._state];
  }

  Map<String, List> get area {
    return {..._area};
  }

  List<String> get propertyCategory {
    return [..._propertyCategory];
  }

  Map<String, List> get propertyType {
    return {..._propertyType};
  }

  List<String> get titleType {
    return [..._titleType];
  }

  List<String> get adType {
    return [..._adType];
  }

  List<String> get bedrooms {
    return [..._bedrooms];
  }

  List<String> get bathroom {
    return [..._bathroom];
  }

  List<String> get otherInfo {
    return [..._otherInfo];
  }

  final List<String> _state = [
    'Johor',
    'Kedah',
    'Kelantan',
    'Kuala Lumpur',
    'Labuan',
    'Melaka',
    'Negeri Sembilan',
    'Pahang',
    'Penang',
    'Perak',
    'Perlis',
    'Putrajaya',
    'Selangor',
    'Sabah',
    'Sarawak',
    'Terengganu'
  ];

  final List<String> _titleType = ['Freehold', 'Leasehold'];
  final List<String> _adType = ['For Sale', 'For Rent'];

  final List<String> _bedrooms = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    'More than 10'
  ];

  final List<String> _bathroom = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    'More than 10'
  ];

  final List<String> _otherInfo = [
    'Bumi Lot',
    'Non Bumi Lot',
    'Malay Reserved'
  ];

  final List<String> _propertyCategory = [
    'Apartments',
    'Houses',
    'Commercial Properties',
    'Land',
    'Rooms'
  ];

  final Map<String, List> _propertyType = {
    'Apartments': [
      'Flat',
      'Apartment',
      'Condominium',
      'Service Residence',
      'Studio',
      'Duplex',
      'Townhouse Condo',
      'Others'
    ],
    'Houses': [
      'Bungalow House',
      'Link Bungalow',
      'Zero-Lot Bungalow',
      'Semi-Detached House',
      'Cluster House',
      'Terraced House',
      '1-storey Terraced House',
      '1.5-storey Terraced House',
      '2-storey Terraced House',
      '2.5-storey Terraced House',
      '3-storey Terraced House',
      '3.5-storey Terraced House',
      'Townhouse',
      'Twin Villas',
      'Twin Courtyard Villa',
      'Others'
    ],
    'Commercial Properties': [
      'Office space',
      'Retail space',
      'Shop lot',
      'Warehouse / Factory',
      'Hotel / Resort',
      'Sofo',
      'Soho',
      'Sovo',
      'Others'
    ],
    'Land': [
      'Residential',
      'Industrial',
      'Agricultural',
      'Commercial',
      'Mixed Development',
      'Others'
    ],
    'Rooms': [
      'Condo / Services residence / Penthouse / Townhouse',
      'Apartment / Flat',
      'Houses',
      'Shoplot',
      'Sharing a house / Flat',
      'Others'
    ]
  };

  final Map<String, List> _area = {
    'Johor': [
      'Ayer Baloi',
      'Ayer Hitam',
      'Ayer Tawar 2',
      'Bakri',
      'Bandar Penawar',
      'Bandar Tenggara',
      'Batu Anam',
      'Batu Pahat',
      'Bekok',
      'Benut',
      'Bukit Gambir',
      'Bukit Pasir',
      'Chaah',
      'Endau',
      'Gelang Patah',
      'Gerisek',
      'Gugusan Taib Andak',
      'Jementah',
      'Johor Bahru',
      'Kahang',
      'Kluang',
      'Kota Tinggi',
      'Kukup',
      'Kulai',
      'Labis',
      'Layang-Layang',
      'Masai',
      'Mersing',
      'Muar',
      'Nusajaya',
      'Pagoh',
      'Paloh',
      'Panchor',
      'Parit Jawa',
      'Parit Raja',
      'Parit Sulong',
      'Pasir Gudang',
      'Pekan Nenas',
      'Pengerang',
      'Pontian',
      'Pulau Satu',
      'Rengam',
      'Rengit',
      'Segamat',
      'Semerah',
      'Senai',
      'Senggarang',
      'Seri Gading',
      'Seri Medan',
      'Simpang Rengam',
      'Sungai Mati',
      'Tangkak',
      'Ulu Tiram',
      'Yong Peng',
      'Others'
    ],
    'Kedah': [
      'Alor Setar',
      'Ayer Hitam',
      'Baling',
      'Bandar Baharu',
      'Bedong',
      'Bukit Kayu Hitam',
      'Changloon',
      'Gurun',
      'Jeniang',
      'Jitra',
      'Karangan',
      'Kepala Batas',
      'Kodiang',
      'Kota Kuala Muda',
      'Kota Sarang Semut',
      'Kuala Kedah',
      'Kuala Ketil',
      'Kuala Nerang',
      'Kuala Pegang',
      'Kulim',
      'Kupang',
      'Langgar',
      'Langkawi',
      'Lunas',
      'Merbok',
      'Padang Serai',
      'Pendang',
      'Pokok Sena',
      'Serdang',
      'Sik',
      'Simpang Empat',
      'Sungai Petani',
      'Universiti Utara Malaysia',
      'Yan',
      'Others'
    ],
    'Kelantan': [
      'Ayer Lanas',
      'Bachok',
      'Cherang Ruku',
      'Dabong',
      'Gua Musang',
      'Jeli',
      'Kem Desa Pahlawan',
      'Ketereh',
      'Kota Bharu',
      'Kuala Balah',
      'Kuala Krai',
      'Machang',
      'Melor',
      'Pasir Mas',
      'Pasir Puteh',
      'Pulai Chondong',
      'Rantau Panjang',
      'Selising',
      'Tanah Merah',
      'Temangan',
      'Tumpat',
      'Wakaf Bharu',
      'Others'
    ],
    'Kuala Lumpur': [
      'Ampang Hilir',
      'Bandar Damai Perdana',
      'Bandar Menjalara',
      'Bangsar',
      'Bangsar South',
      'Batu',
      'Brickfields',
      'Bukit Bintang',
      'Bukit Jalil',
      'Bukit Ledang',
      'Bukit Persekutuan',
      'Bukit Tunku',
      'Cheras',
      'City Centre',
      'Country Heights',
      'Country Heights Damansara',
      'Damansara',
      'Damansara Heights',
      'Desa Pandan',
      'Desa ParkCity',
      'Desa Petaling',
      'Gombak',
      'Jalan Ampang',
      'Jalan Ipoh',
      'Jalan Kuching',
      'Jalan Sultan Ismail',
      'Jinjang',
      'Kenny Hills',
      'Kepong',
      'Keramat',
      'KL City',
      'KL Sentral',
      'KLCC',
      'Kunchai Lama',
      'Mid Valley City',
      'Mont Kiara',
      'Old Klang Road',
      'OUG',
      'Pandan Indah',
      'Pandan Jaya',
      'Pandan Perdana',
      'Pantai',
      'Pekan Batu',
      'Puchong',
      'Salak Selatan',
      'Segambut',
      'Sentul',
      'Seputeh',
      'Serdang',
      'Setapak',
      'Setia Eco Park',
      'Setiawangsa',
      'Solaris Dutamas',
      'Sri Damansara',
      'Sri Hartamas',
      'Sri Petaling',
      'Sungai Besi',
      'Sungai Penchala',
      'Taman Desa',
      'Taman Duta',
      'Taman Melawati',
      'Taman Tun Dr Ismail',
      'Taman Permata',
      'Titiwangsa',
      'TPM',
      'Wangsa Maju'
          'Others'
    ],
    'Labuan': [
      'Batu Arang',
      'Batu Manikar',
      'Bebuloh',
      'Belukut',
      'Bukit Kalam',
      'Bukit Kuda',
      'Durian Tunjung',
      'Ganggarak',
      'Gersik',
      'Kilan',
      'Lajau',
      'Layang-Layangan',
      'Lubok Temiang',
      'Nagalang',
      'Pantai',
      'Patau-Patau 1',
      'Patau-Patau 2',
      'Pohon Batu',
      'Rancha-Rancha',
      'Sungai Bedaun',
      'Sungai Bangat',
      'Sungai Buton',
      'Sungai Keling',
      'Sungai Lada',
      'Sungai Labu',
      'Sungai Miri',
      'Tanjung Aru',
      'Others'
    ],
    'Melaka': [
      'Alor Gajah',
      'Asahan',
      'Ayer Keroh',
      'Bandar Hilir',
      'Batu Berendam',
      'Bemban',
      'Bukit Beruang',
      'Durian Tunggal',
      'Jasin',
      'Kuala Linggi',
      'Kuala Sungai Baru',
      'Lubok China',
      'Masjid Tanah',
      'Melaka Tengah',
      'Merlimau',
      'Selandar',
      'Sungai Rambai',
      'Sungai Udang',
      'Tanjong Kling',
      'Ujong Pasir',
      'Others'
    ],
    'Negeri Sembilan': [
      'Bahau',
      'Bandar Enstek',
      'Bandar Baru Serting',
      'Bandar Seri Jempol',
      'Batang Melaka',
      'Batu Kikir',
      'Gemas',
      'Gemencheh',
      'Jelebu',
      'Jempol',
      'Johol',
      'Juasseh',
      'Kota',
      'Kuala Klawang',
      'Kuala Pilah',
      'Labu',
      'Lenggeng',
      'Linggi',
      'Mantin',
      'Niai',
      'Pasir Panjang',
      'Pedas',
      'Port Dickson',
      'Pusat Bandar Palong',
      'Rantau',
      'Rembau',
      'Rompin',
      'Senawang',
      'Seremban',
      'Siliau',
      'Simpang Durian',
      'Simpang Pertang',
      'Sri Menanti',
      'Si Rusa',
      'Tampin',
      'Tanjong Ipoh',
      'Others'
    ],
    'Pahang': [
      'Balok',
      'Bandar Bera',
      'Bandar Pusat Jengka',
      'Bandar Tun Abdul Razak',
      'Benta',
      'Bentong',
      'Brinchang',
      'Bukit Fraser',
      'Bukit Goh',
      'Bukit Kuin',
      'Chenor',
      'Chini',
      'Daerah Rompin',
      'Damak',
      'Dong',
      'Gambang',
      'Genting Highlands',
      'Jerantut',
      'Karak',
      'Kemayan',
      'Kuala Krau',
      'Kuala Lipis',
      'Kuala Rompin',
      'Kuantan',
      'Lanchang',
      'Lurah Bilut',
      'Maran',
      'Mengkarak',
      'Mentakab',
      'Muadzam Shah',
      'Padang Tengku',
      'Pekan',
      'Raub',
      'Ringlet',
      'Rompin',
      'Sega',
      'Sungai Koyan',
      'Sungai Lembing',
      'Sungai Ruan',
      'Tanah Rata',
      'Temerloh',
      'Triang',
      'Others'
    ],
    'Penang': [
      'Ayer Tawar',
      'Alma',
      'Ayer Itam',
      'Bagan Ajam',
      'Bagan Jermal',
      'Bagan Lalang',
      'Balik Pulau',
      'Batu Ferringhi',
      'Batu Maung',
      'Batu Uban',
      'Batu Baru',
      'Bayan Lepas',
      'Berapit',
      'Bertam',
      'Bukit Dumbar',
      'Bukit Jambul',
      'Bukit Mertajam',
      'Bukit Minyak',
      'Bukit Tambun',
      'Bukit Tengah',
      'Butterworth',
      'Gelugor',
      'Georgetown',
      'Gertak Sangul',
      'Greenlane',
      'Jawi',
      'Jelutong',
      'Juru',
      'Kepala Batas',
      'Kubang Semang',
      'Mak Mandin',
      'Minden Heights',
      'Nibong Tebal',
      'Pauh Jaya',
      'Paya Terubong',
      'Penaga',
      'Penang Hill',
      'Penanti',
      'Perai',
      'Permatang Kuching',
      'Permatang Pauh',
      'Permatang Tinggi',
      'Persiaran Gurney',
      'Prai',
      'Pulau Betong',
      'Pulau Tikus',
      'Raja Uda',
      'Relau',
      'Scotland',
      'Seberang Jaya',
      'Seberang Perai',
      'Simpang Ampat',
      'Sungai Ara',
      'Sungai Bakap',
      'Sungai Dua',
      'Sungai Jawi',
      'Sungai Nibong',
      'Sungai Pinang',
      'Tanjong Tokong',
      'Tanjung Bungah',
      'Tasek Gelugor',
      'Teluk Bahang',
      'Teluk Kumbar',
      'USM',
      'Valdor',
      'Others'
    ],
    'Perak': [
      'Ayer Tawar',
      'Bagan Datoh',
      'Bagan Serai',
      'Bandar Seri Iskandar',
      'Batu Gajah',
      'Batu Kurau',
      'Behrang Stesen',
      'Bidor',
      'Bota',
      'Bruas',
      'Changkat Jering',
      'Changkat Keruing',
      'Chemor',
      'Chenderiang',
      'Chenderong Balai',
      'Chikus',
      'Enggor',
      'Gerik',
      'Gopeng',
      'Hutan Melintang',
      'Intan',
      'Ipoh',
      'Jeram',
      'Kampar',
      'Kampung Gajah',
      'Kampung Kepayang',
      'Kamunting',
      'Kuala Kangsar',
      'Kuala Kurau',
      'Kuala Sepetang',
      'Lambor Kanan',
      'Langkap',
      'Lenggong',
      'Lumut',
      'Malim Nawar',
      'Manong',
      'Matang',
      'Padang Rengas',
      'Pangkor',
      'Pantai Remis',
      'Parit',
      'Parit Buntar',
      'Pengkalan Hulu',
      'Pusing',
      'Rantau Panjang',
      'Sauk',
      'Selama',
      'Selekoh',
      'Seri Manjong',
      'Simpang',
      'Simpang Ampat Semanggol',
      'Sitiawan',
      'Slim River',
      'Sungai Siput',
      'Sungai Sumun',
      'Sungkai',
      'Taiping',
      'Tanjong Malim',
      'Tanjong Piandang',
      'Tanjong Rambutan',
      'Tanjong Tualang',
      'Tapah',
      'Tapah Road',
      'Teluk Intan',
      'Temoh',
      'TLDM Lumut',
      'Trolak',
      'Trong',
      'Tronoh',
      'Ulu Bernam',
      'Ulu Kinta',
      'Others'
    ],
    'Perlis': [
      'Arau',
      'Kaki Bukit',
      'Kangar',
      'Kuala Perlis',
      'Padang Besar',
      'Pauh',
      'Simpang Ampat',
      'Others'
    ],
    'Putrajaya': ['Putrajaya', 'Others'],
    'Selangor': [
      'Alam Impian',
      'Aman Perdana',
      'Ampang',
      'Ambang Botanic',
      'Ara Damansara',
      'Balakong',
      'Bandar Botanic',
      'Bandar Bukit Raja',
      'Bandar Bukit Tinggi',
      'Bandar Kinrara',
      'Bandar Puteri Klang',
      'Bandar Puteri Puchong',
      'Bandar Saujana Putra',
      'Bandar SUngai Long',
      'Bandar Sunway',
      'Bandar Utama',
      'Bangi',
      'Banting',
      'Batang Berjuntai',
      'Batang Kali',
      'Batu Arang',
      'Batu Caves',
      'Beranang',
      'Bukit Beruntung',
      'Bukit Jelutong',
      'Bukit Rahman Putra',
      'Bukit Rotan',
      'Bukit Subang',
      'Cheras',
      'Country Heights',
      'Cyberjaya',
      'Damansara Damai',
      'Damansara Intan',
      'Damansara Jaya',
      'Damansara Kim',
      'Damansara Perdana',
      'Damansara Utama',
      'Denai Alam',
      'Dengkil',
      'Glenmarie',
      'Gombak',
      'Hulu Langat',
      'Hulu Selangor',
      'Jenjarom',
      'Kajang',
      'Kapar',
      'Kayu Ara',
      'Kelana Jaya',
      'Kerling',
      'Klang',
      'Kota Damansara',
      'Kota Emerald',
      'Kota Kemuning',
      'Kuala Kubu Baru',
      'Kuala Langat',
      'Kuala Selangor',
      'Kuang',
      'Mutiara Damansara',
      'Petaling Jaya',
      'Port Klang',
      'Puchong',
      'Puchong South',
      'Pulau Indah',
      'Pulau Carey',
      'Pulau Ketam',
      'Puncak Alam',
      'Puncak Jalil',
      'Putra Heights',
      'Rasa',
      'Rawang',
      'Sabak Bernam',
      'Salak Tinggi',
      'Saujana',
      'Saujana Utama',
      'Sekinchan',
      'Selayang',
      'Semenyih',
      'Sepang',
      'Serdang',
      'Serendah',
      'Seri Kembangan',
      'Setia Alam',
      'Setia Eco Park',
      'Shah Alam',
      'SierraMas',
      'SS2',
      'Subang Bestari',
      'Subang Heights',
      'Subang Jaya',
      'Subang Perdana',
      'Sungai Ayer Tawar',
      'Sungai Besar',
      'Sungai Buloh',
      'Sungai Pelek',
      'Taman TTDI Jaya',
      'Tanjong Karang',
      'Tanjong Sepat',
      'Telok Panglima Garang',
      'Tropicana',
      'Ulu Klang',
      'USJ',
      'USJ Heights',
      'Valencia',
      'Others'
    ],
    'Sabah': [
      'Beaufort',
      'Beluran',
      'Beverly',
      'Bongawan',
      'Inanam',
      'Keningau',
      'Kota Belud',
      'Kota Kinabalu',
      'Kota Kinabatangan',
      'Kota Marudu',
      'Kuala Penyu',
      'Kudat',
      'Kunak',
      'Lahad Datu',
      'Likas',
      'Membakut',
      'Menumbok',
      'Nabawan',
      'Pamol',
      'Papar',
      'Penampang',
      'Putatan',
      'Ranau',
      'Sandakan',
      'Semporna',
      'Sipitang',
      'Tambunan',
      'Tamparuli',
      'Tanjung Aru',
      'Tawau',
      'Tenghilan',
      'Tenom',
      'Tuaran',
      'Others'
    ],
    'Sarawak': [
      'Asajaya',
      'Balingian',
      'Baram',
      'Bau',
      'Bekenu',
      'Belaga',
      'Belawi',
      'Betong ',
      'Bintangor',
      'Bintulu',
      'Dalat',
      'Daro',
      'Debak',
      'Engkilili',
      'Jalau',
      'Kabong',
      'Kanowit',
      'Kapit',
      'Kota Samarahan',
      'Kuching',
      'Lawas',
      'Limbang',
      'Lingga',
      'Long Lama',
      'Lubuk Antu',
      'Lundu',
      'Lutong',
      'Maradong',
      'Marudi',
      'Matu',
      'Miri',
      'Mukah',
      'Nanga Medamit',
      'Niah',
      'Pusa',
      'Roban',
      'Saratok',
      'Sarikei',
      'Sebauh',
      'Sebuyau',
      'Serian',
      'Sibu',
      'Simunjan',
      'Song',
      'Spaoh',
      'Sri Aman',
      'Sundar',
      'Tanjung Kidurong',
      'Tatau',
      'Others'
    ],
    'Terengganu': [
      'Besut',
      'Dungun',
      'Hulu Terengganu',
      'Kemaman',
      'Kuala Terengganu',
      'Marang',
      'Setiu',
      'Kuala Nerus',
      'Others'
    ]
  };
}
